### ISSUE TITLE
Venue classifier

### ISSUE THREAD

**Issue by gavra0** [thesign0/bd914#10]
By analyzing data that is accessible (https://github.com/icyc0re/bd914/wiki/Available-data), suggest which venue properties we would extract and use in order to classify the venues.
Book found on https://github.com/icyc0re/bd914/wiki/Literature containt explanations about the topic.

**Comment by swiatkowski** [comment]
I can look into it. I think this is one of the key parts in our project. Therefore I will need to get some more knowledge about recommender systems before coming up with venue features that we will use in our system  :)
