### ISSUE TITLE
User profiling

### ISSUE THREAD

**Issue by gavra0** [thesign0/bd914#11]
By analyzing data that is accessible (https://github.com/icyc0re/bd914/wiki/Available-data), in cooperation with person that is working on #10, suggest a representation that we could use for the user profiles.
Describe the way how we can extract those features and how to use them.

**Comment by perovic** [comment]
13a0632c91d61c5486e74edbcfa74ebf929acd46 addresses this. The summary describes all the data that could potentially be useful. After we have definitely defined how to model venue feature vectors, we will specify the exact data by which we will create the user feature preference vector.
