### ISSUE TITLE
User statistics

### ISSUE THREAD

**Issue by gavra0** [thesign0/bd914#18]
Similar to #16 , find the statistics for the available user properties that could be useful for user profiling.

It would especially be interesting to find the distribution of the number of venues that we have per user (basically how many times does user appears in the interactions for different venues). Sample of the user data is available in https://github.com/icyc0re/bd914/blob/master/dataset/sample/users/user.json 

After the pulling of the information about the users from the venues is done (which should happen in two/three days), the statistics algorithm can be run on that data. For start, make it functional only on the data available in https://github.com/icyc0re/bd914/blob/master/dataset/sample

**Comment by maccari** [comment]
closed by ecea66c
