### ISSUE TITLE
Process 4SQ data - venues & users

### ISSUE THREAD

**Issue by gavra0** [thesign0/bd914#2]
Using the obtained data on /data/team14 (icdatasrv4), create a feature vector representation of the venues and users. Do not focus on choosing the features (that will be done in #11 and #10 ), but create an extensible extracting mechanism.

Check scala foursquare api https://github.com/nfolkert/scala-foursquare-api, and consider other ways of accomplishing this if that libarary is not working.

**Comment by mpagli** [comment]
A basic version has been committed. I put a test venue in the recommender_module folder and a small demonstration in RecommenderApp.scala. All the features are not extracted yet but people can start using this to create a first version of the recommender.
