### ISSUE TITLE
Postfiltering component

### ISSUE THREAD

**Issue by gavra0** [thesign0/bd914#28]
Apply the contextual parameters after the basic rankings have been calculated. In the phase before this, rankings are calculated based on the values of venue features and user features, and this phase should fine-tune the results.

Define the math model that we use for this component, and propose how each of the contextual parameters affects the final venue ranking.

**Comment by sprlye** [comment]
Yep, i'll continue on that :)

**Comment by sprlye** [comment]
Finished the first version.
