### ISSUE TITLE
Recommendation System

### ISSUE THREAD

**Issue by gavra0** [thesign0/bd914#3]
By observing the system and available data, try to find the suitable model to implement the recommendation system. Our approach is going to be to find an appropriate model for our prediction and use machine learning algorithms to adjust the parameters of the model. There will be going back and forth between defining the fitness function and testing the model.

@ardy15jan & @jakubswiatkowski : machine learning approaches
@mpagli & @perovic : research statistical models
@sprlye : research Wekka

**Comment by mpagli** [comment]
Hi, I'd like to set up a brainstorming platform so we can gather and process information coherently. I was thinking of co-creating a mindmap on either lucidchart or coggle. Both are really easy to use. My preference goes for coggle, I started crawling : 

https://coggle.it/diagram/5328790c1542be8205002675/95b778b32bfafdec32a4cc2bf8629bc10d7a9c916f7e3b8accf4e666dbaf44d0

best

**Comment by gavra0** [comment]
This looks awesome :+1:

**Comment by ElSeidy** [comment]
Ahaaaaa ... now we're talking :+1:

**Comment by gavra0** [comment]
This task is no longer valid, because more specific sub-tasks have been created.
