### ISSUE TITLE
similitude between two categories

### ISSUE THREAD

**Issue by maccari** [thesign0/bd914#31]
In order to get similitudes between venue<->venue or venue<->user, implement a method to compute the similitudes between two categories, using the tree from https://developer.foursquare.com/categorytree or the json in https://github.com/icyc0re/bd914/blob/master/dataset/categories.

Two sub-categories with a different parent should return 0.
Two sub-categories with a common parent returns the depth of this parent.

So the bigger the depth, the bigger the similitude between the categories.

**Comment by thesign0** [comment]
closed by commit dc5731846f1ba9f7aaf6976618cd36b10914fb6f
