### ISSUE TITLE
Contextual vector - Time

### ISSUE THREAD

**Issue by gavra0** [thesign0/bd914#39]
Parse the time property and add it to the post/pre filtering phase, according to @emmahf 's paper (0, 0.5, 1).

**Comment by sprlye** [comment]
I just pushed that. It's not added yet to the post/pre filter, i need the context vector for that. I'll do it for a random context vector soon, so then we can just plug the real one.

**Comment by sprlye** [comment]
It's done! Still with dummy context vectors though.
