### ISSUE TITLE
Website prototype

### ISSUE THREAD

**Issue by gavra0** [thesign0/bd914#4]
Make the basic UI, no customization. Try to find some template that we can use, and that will not take too much time to adjust to our needs.

Website should consists from the following parts:
- Input screen where user identifies him/herself. This can be a simple page with a couple of sliders by which user is expressing preferences towards certain characteristics of the venues.
- Output screen which shows Foursquare venues on the map that are recommended to this user, after the request has been processed.

For this prototype use only mock data. Also, lay down architecture so that we can easily switch from mock data to real data sources.

@icyc0re : website development
@emmahf : visualizations

**Comment by emmahf** [comment]
For visualization I want to add to not only show the recommendations on the map but also to display some of the information on these recommended venues, for example what we have calculated about the venues (i.e. popularity (#check-ins), or gender distribution, category etc) - maybe separate the tasks?
