### ISSUE TITLE
Provide small data set

### ISSUE THREAD

**Issue by gavra0** [thesign0/bd914#8]
Provide small data set containing 10 venues and all of the users that interacted with those venues. This way team that is working on the recommender can have an idea what is the real data like.

**Comment by maccari** [comment]
Just added a small dataset of 100 venues in dataset/sample/venues.
They are indented thus can be read directly.
I'll add a small python script on how to load them to play around.

**Comment by maccari** [comment]
Just added users that interacted with sample venues.
